license="MIT License"
modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN/issues"
[[mods]]
modId="splan"
version="2.70"
displayName="Server Properties for LAN"
displayURL="https://github.com/shuen4/MinecraftForge-Mods-ServerPropertiesLAN"
logoFile="logo.png"
authors="Jaideep Singh Heer,sotzaii_shuen"
description='''
This mod creates a server.properties file inside every world folder and forces your LAN World to use the settings in this file.
'''