license="MIT License"
modLoader="javafml" #mandatory
loaderVersion="[25,)"
[[mods]]
modId="splan" #mandatory
version="2.67" #mandatory
displayName="Server Properties for LAN"
displayURL="https://minecraft.curseforge.com/projects/server-properties-for-lan" #optional
logoFile="logo.png"
authors="Jaideep Singh Heer,sotzaii_shuen"
description='''
This mod creates a server.properties file inside every world folder and forces your LAN World to use the settings in this file.
'''
